FACT/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^orden/$', views.orden, name ='orden'),
    url(r'^ListarOrdenes/$', views.OrdenLista.as_view(), name='ListarOrdenes'),
    url(r'^crearOrden/$', views.crearOrden, name='crearOrden'),
]

P11/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fact/', include('FACT.urls', namespace= 'fact')),
]

FACT/models.py
from __future__ import unicode_literals

from django.db import models

from django.db import models
class Orden(models.Model):
    id= models.IntegerField
    descripcion= models.CharField(max_length=1000, null=True)
    proveedor = models.CharField(max_length=1000, null=True)
    costo= models.IntegerField (null=True)

FACT/views.py
import datetime
import json
from FACT import serializers
from django.core import serializers
from .models import Orden
from django.shortcuts import render
from rest_framework import generics
from rest_framework import viewsets
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser

from .models import Orden
from .serializers import OrdenSerializer
from rest_framework import generics


def index(request):
    lista_imagenes = Orden.objects.all()
    context = {'lista_imagenes': lista_imagenes}
    return render(request, 'fact/index.html', context)

@csrf_exempt
def orden(request):
    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = OrdenSerializer(data=data)
        print (data)
        print (serializer)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)
    elif request.method == 'GET':
        orden = Orden.objects.all()
        return HttpResponse(serializers.serialize("json", orden))
class OrdenLista(generics.ListAPIView):
    serializer_class = OrdenSerializer
    def get_queryset(self):
        orden = Orden.objects.all()
        return orden


def crearOrden(request):
    return render(request, 'fact/orden/agregarOrden.html')

FACT/templates/fact/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"-->
    <!--link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/global.css' %}" rel="stylesheet">
    <script
            src="https://code.jquery.com/jquery-3.2.1.js"
    		integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
    		crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--script src="{% static 'js/factController.js'%} "></script-->
    <script type="application/javascript">
        var urlAll = "{% url 'fact:ListarOrdenes'%}";
        var host ="https://{{ request.META.HTTP_HOST }}";
        $(document).ready(function () {
                var table = $('#myTable').DataTable( {
        "ajax": {
            "url":  host+urlAll,
            "dataSrc": ""
        },
        "columns": [
            { data: "descripcion" },
            { data: "proveedor" },
            { data: "costo" },
        ]
        } );


        });
    </script>
</head>
<body>
        <div class="container">
            <h1 class="text-center" style="color:#fed136">Ordenes</h1>
            <div class="row">
                <div class="datagrid ">
                    <table id="myTable" class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Descripción</th>
                                <th>Proveedor</th>
                                <th>Costo</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
             </div>
         </div>
    </section>
</body>
</html>

FACT/templates/fact/orden/agregarOrden.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <section>
        <div class="container">
            <h1 class="text-center" style="color:#fed136">Crear Orden</h1>
            <form class="form-horizontal" method="POST" data-project-url="{%url 'fact:orden'%}" id="formProject">
            {%csrf_token%}
                <div class="form-group">
                    <label for="nombre" class="col-sm-2 control-label">Titulo: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="text" name="nombre" id="nombre" maxlength="100" value=""  autofocus placeholder="Nombre del proyecto">
                    </div>
                </div>
                <div class="form-group">
                    <label for="fechaInicio" class="col-sm-2 control-label">Fecha de inicio: </label>
                    <div class="col-sm-6">
                        <input type="date" name="fechaInicio" id="fechaInicio" value="" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="fechaFinal"class="col-sm-2 control-label">Fecha de finalización: </label>
                    <div class="col-sm-6">
                        <input type="date" name="fechaFinal" id="fechaFinal" value="" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="patrocinador" class="col-sm-2 control-label">Patrocinador: </label>
                    <div class="col-sm-6">
                        <select class="form-control" name="patrocinador" id="patrocinador">
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="Estado" class="col-sm-2 control-label">Estado: </label>
                    <div class="col-sm-6">
                        <select class="form-control" name="estado" id="estado">
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="prioridad" class="col-sm-2 control-label">Prioridad: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="number"  name="prioridad" id="prioridad" value="0" placeholder="Prioridad (0-100)" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="descripcion" class="col-sm-2 control-label">Descripción: </label>
                    <div class="col-sm-6">
                        <textarea class="form-control" name="descripcion"  cols="100" rows="5" id="descripcion" > </textarea>
                    </div>
                </div>
                <div class="col-sm-offset-4 col-sm-10">
                    <input class="btn btn-warning" type="button" onclick="validateData(true)" value="Guardar"/>
                    <a href="{% url 'laboratorio:listarProyectos' %}" class="btn btn-warning">Regresar</a>
                </div>
            </form>
        </div>
    </section>
</body>
</html>

templates/FACT/orden/agregarOrden.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <section>
        <div class="container">
            <h1 class="text-center" style="color:#fed136">Crear Orden</h1>
            <form class="form-horizontal" method="POST" data-project-url="{%url 'FACT:orden'%}" id="formProject">
            {%csrf_token%}
                <div class="form-group">
                    <label for="nombre" class="col-sm-2 control-label">Titulo: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="text" name="nombre" id="nombre" maxlength="100" value=""  autofocus placeholder="Nombre del proyecto">
                    </div>
                </div>
                <div class="form-group">
                    <label for="fechaInicio" class="col-sm-2 control-label">Fecha de inicio: </label>
                    <div class="col-sm-6">
                        <input type="date" name="fechaInicio" id="fechaInicio" value="" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="fechaFinal"class="col-sm-2 control-label">Fecha de finalización: </label>
                    <div class="col-sm-6">
                        <input type="date" name="fechaFinal" id="fechaFinal" value="" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="patrocinador" class="col-sm-2 control-label">Patrocinador: </label>
                    <div class="col-sm-6">
                        <select class="form-control" name="patrocinador" id="patrocinador">
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="Estado" class="col-sm-2 control-label">Estado: </label>
                    <div class="col-sm-6">
                        <select class="form-control" name="estado" id="estado">
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="prioridad" class="col-sm-2 control-label">Prioridad: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="number"  name="prioridad" id="prioridad" value="0" placeholder="Prioridad (0-100)" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="descripcion" class="col-sm-2 control-label">Descripción: </label>
                    <div class="col-sm-6">
                        <textarea class="form-control" name="descripcion"  cols="100" rows="5" id="descripcion" > </textarea>
                    </div>
                </div>
                <div class="col-sm-offset-4 col-sm-10">
                    <input class="btn btn-warning" type="button" onclick="validateData(true)" value="Guardar"/>
                    <a href="{% url 'laboratorio:listarProyectos' %}" class="btn btn-warning">Regresar</a>
                </div>
            </form>
        </div>
    </section>
</body>
</html>